name: jmc_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.7.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10
  sqflite: ^2.4.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  
flutter:

  uses-material-design: true

  assets:
    - assets/
