name: jmc_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.7.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10
  sqflite: ^2.4.0
  pull_to_refresh: ^2.0.0
  flutter_webrtc: ^0.12.1
  shared_preferences: ^2.3.2
  http: ^1.2.2
  path_provider: ^2.1.4
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  cloud_firestore_web: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  
flutter:

  uses-material-design: true

  assets:
    - assets/
