// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXJzL-tU9K11s-uhXIyKP-cfJ2Ql3JJ90',
    appId: '1:302602482078:web:72f6d746251321a6e6668f',
    messagingSenderId: '302602482078',
    projectId: 'culture-monitoring-system',
    authDomain: 'culture-monitoring-system.firebaseapp.com',
    storageBucket: 'culture-monitoring-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvVv3TB8qn-OM51wNSbGs4e81VMuCLo5Y',
    appId: '1:302602482078:android:6ec0ac16e97eac44e6668f',
    messagingSenderId: '302602482078',
    projectId: 'culture-monitoring-system',
    storageBucket: 'culture-monitoring-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFkkbrT22RDGhOVqZXd8A-c9L0cmZvMko',
    appId: '1:302602482078:ios:a7e70b5b15cb4bfbe6668f',
    messagingSenderId: '302602482078',
    projectId: 'culture-monitoring-system',
    storageBucket: 'culture-monitoring-system.appspot.com',
    iosBundleId: 'com.syahrul.jmcTest',
  );
}
